---
title: "Proposal title"
subtitle: "Proposal"
author: 
  - name: "Team Drew Maichle - Drew Maichle"
    affiliations:
      - name: "College of Information Science, University of Arizona"
description: "Project description"
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
jupyter: python3
---

```{python}
#| label: load-pkgs
#| message: false
import numpy as np
import pandas as pd
import nfl_data_py as nfl
```

## Dataset

```{python}
#| label: load-dataset
#| message: false
# Load data in Python
final_df = pd.read_csv('data/nfl_2024_games_with_dvoa.csv')
# Display the first few rows of the final DataFrame
print("\Loaded Final DataFrame from CSV")
print(final_df.head())
# Print column names to verify
print("Column Names:")
print(final_df.columns.tolist())
#Print DataFrame info
print("DataFrame Info:")
print(final_df.info())
#Print DataFrame description
print("DataFrame Description:")
print(final_df.describe())
#print data types of each column
print("Data Types of Each Column:")
print(final_df.dtypes)
#data shape
print(final_df.shape)
```

This dataset was pulled from the nfl_data_py library. I pulled game data for the 272 games in the 2024 regular season.
This base data contains a game identifer, home and away teams, and scores for both teams. In addition, I generated DVOA for all teams
and applied a column displaying the DVOA of each team along with the differential (home dvoa - away). DVOA is a well known proprietary
metric stemming from ftn fantasy that factors in performance from each snap
## Data Access
please view the nfl_2024_games_with_dvoa file in data
##Description of observations
My file has the following colums:
 game_id: game identifier in the format of game_week_away team_home team
 season: what year is the season
 week: What week number is the game being played on
 away_team: Two or three letter indicator of what team is playing away from home
 home_team: Two or three letter indicator of what team is playing at home
 away score: Number of points scored by away team
 home score: Number of points scored by home team
 game: indentifier in the format away_team @ home_team
 home_dvoa: performance metric Defense-adjusted Value Over Average for home team
 away_dvoa: performance metric Defense-adjusted Value Over Average for away team
 dvoa_diff: home_dvoa - away_dvoa

##Ethical Concerns
The NFL game data is publicly available so there are no ethical Concerns for that data. DVOA is considered a proprietary metric and 
total DVOA which I am utilizing is publicly available. Ideally, I would be implementing this split into offensive and defensive DVOA 
however this is not publicly available along with this statistic being adjusted week by week. I beleive that I have adressed this in an
 ethical way.
## Questions

The two questions you want to answer.
What is the correlation of stats such as DVOA (Defense-adjusted Value Over Average) and scores within my 2024 dataset?
Can I create an algorithm that can predict predict the NFL matchups based on training data?

## Analysis plan

-   A plan for answering each of the questions including the variables involved, variables to be created (if any), external data to be merged in (if any).
My dataset will contain these matchups and I can run a correlation matrix to see what the correlation is between these variables.
For the first question, I can run a correlation matrix and use python tools to provide a correlation of my target features
To answer the second question, I can feed an algorith with data with team identifiers, performance metrics such as DVOA
 DOVA, rest days (if I can find the metrics), and winning percentage (to that point in the season), for each team in the matchup.
I will also have points scored for each team and divide my dataset into training and test sets. From there I can use a model such as
random tree to predict winners for each matchup. If I have time, I would like to see if I can find a way to add more data columns such
as how many days of rest a team is on to see if I can improve predicatability
